# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e31076703a285f70bcefd8a2988151843f07e0aea3751c8438ba9178bcb7717091a8cd7e0385cc7ad1ac6982624721c57e70e4b5a78ac272c4398d688ccb427e

test:
  secret_key_base: 7d67485aa373939c8fb78f1a76f2b7b10b78cebe6cfe17f50524184f308a7e7261a46f66cf317adb5f4d5e041543a221c0af5ec73f929682a5f5a897df5920b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
